import { TarotCard } from '../types/tarot';

/**
 * Complete 78-card Rider-Waite-Smith inspired tarot deck data.
 * 22 Major Arcana + 56 Minor Arcana (4 suits × 14 cards).
 */
export const TAROT_DECK: TarotCard[] = [
  // ─────────────────────────────────────────────
  // MAJOR ARCANA
  // ─────────────────────────────────────────────
  {
    id: 'major-00',
    name: 'The Fool',
    arcana: 'major',
    number: 0,
    keywords: ['beginnings', 'innocence', 'spontaneity', 'free spirit', 'adventure'],
    uprightMeaning:
      'New beginnings, optimism, trust in life. A leap of faith into the unknown with an open heart.',
    reversedMeaning:
      'Naivety, foolishness, recklessness, poor judgment, or holding back from a necessary leap.',
    imageKey: 'major_fool',
  },
  {
    id: 'major-01',
    name: 'The Magician',
    arcana: 'major',
    number: 1,
    keywords: ['willpower', 'skill', 'resourcefulness', 'manifestation', 'action'],
    uprightMeaning:
      'You have the tools and talents to manifest your desires. Focused will transforms intention into reality.',
    reversedMeaning:
      'Manipulation, trickery, untapped potential, or misuse of power.',
    imageKey: 'major_magician',
  },
  {
    id: 'major-02',
    name: 'The High Priestess',
    arcana: 'major',
    number: 2,
    keywords: ['intuition', 'mystery', 'inner knowledge', 'subconscious', 'silence'],
    uprightMeaning:
      'Trust your intuition. Hidden truths will reveal themselves. A time for stillness and inner listening.',
    reversedMeaning:
      'Secrets kept, disconnection from intuition, repressed feelings, or information withheld.',
    imageKey: 'major_high_priestess',
  },
  {
    id: 'major-03',
    name: 'The Empress',
    arcana: 'major',
    number: 3,
    keywords: ['fertility', 'abundance', 'nurturing', 'nature', 'creativity'],
    uprightMeaning:
      'Abundance, creativity, and nurturing energy surround you. A time of growth, beauty, and connection to the natural world.',
    reversedMeaning:
      'Creative block, dependence, smothering energy, or neglecting self-care.',
    imageKey: 'major_empress',
  },
  {
    id: 'major-04',
    name: 'The Emperor',
    arcana: 'major',
    number: 4,
    keywords: ['authority', 'structure', 'stability', 'leadership', 'control'],
    uprightMeaning:
      'Solid foundations, leadership, and order. A time to establish structure and take authoritative action.',
    reversedMeaning:
      'Rigidity, domination, excessive control, or failure to assume responsibility.',
    imageKey: 'major_emperor',
  },
  {
    id: 'major-05',
    name: 'The Hierophant',
    arcana: 'major',
    number: 5,
    keywords: ['tradition', 'conformity', 'spirituality', 'guidance', 'wisdom'],
    uprightMeaning:
      'Seeking wisdom through established traditions, spiritual institutions, or a wise mentor figure.',
    reversedMeaning:
      'Challenging orthodoxy, personal belief systems, rebellion against convention.',
    imageKey: 'major_hierophant',
  },
  {
    id: 'major-06',
    name: 'The Lovers',
    arcana: 'major',
    number: 6,
    keywords: ['love', 'harmony', 'relationships', 'values', 'choices'],
    uprightMeaning:
      'Deep connections, aligned values, and meaningful choices. Love that reflects who you truly are.',
    reversedMeaning:
      'Misalignment, disharmony in relationships, poor decisions, or inner conflict.',
    imageKey: 'major_lovers',
  },
  {
    id: 'major-07',
    name: 'The Chariot',
    arcana: 'major',
    number: 7,
    keywords: ['determination', 'control', 'victory', 'willpower', 'direction'],
    uprightMeaning:
      'Victory through discipline and focused will. You are steering your life forward with confidence.',
    reversedMeaning:
      'Lack of direction, aggression, no control, or obstacles blocking forward movement.',
    imageKey: 'major_chariot',
  },
  {
    id: 'major-08',
    name: 'Strength',
    arcana: 'major',
    number: 8,
    keywords: ['courage', 'patience', 'inner strength', 'compassion', 'gentle power'],
    uprightMeaning:
      'True strength comes from compassion and patience. You have the inner fortitude to face any challenge gracefully.',
    reversedMeaning:
      'Self-doubt, weakness, insecurity, or raw emotion overpowering reason.',
    imageKey: 'major_strength',
  },
  {
    id: 'major-09',
    name: 'The Hermit',
    arcana: 'major',
    number: 9,
    keywords: ['solitude', 'introspection', 'guidance', 'inner wisdom', 'searching'],
    uprightMeaning:
      'A period of solitude and reflection. Turn inward to find the answers you seek through your own inner light.',
    reversedMeaning:
      'Isolation, loneliness, withdrawal from the world, or refusing guidance.',
    imageKey: 'major_hermit',
  },
  {
    id: 'major-10',
    name: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    keywords: ['fate', 'cycles', 'turning point', 'luck', 'destiny'],
    uprightMeaning:
      'A turning point is at hand. Life's cycles bring new opportunities — what rises must eventually fall, and vice versa.',
    reversedMeaning:
      'Bad luck, resistance to change, or feeling trapped by fate.',
    imageKey: 'major_wheel_of_fortune',
  },
  {
    id: 'major-11',
    name: 'Justice',
    arcana: 'major',
    number: 11,
    keywords: ['fairness', 'truth', 'cause and effect', 'law', 'balance'],
    uprightMeaning:
      'Truth, fairness, and karmic balance. Every action has a consequence; the scales will weigh your choices honestly.',
    reversedMeaning:
      'Unfairness, dishonesty, avoiding accountability, or legal complications.',
    imageKey: 'major_justice',
  },
  {
    id: 'major-12',
    name: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    keywords: ['suspension', 'surrender', 'new perspective', 'pause', 'sacrifice'],
    uprightMeaning:
      'Voluntary pause and surrender. A new perspective emerges when you release the need to control.',
    reversedMeaning:
      'Stalling, resistance, meaningless sacrifice, or refusing to let go.',
    imageKey: 'major_hanged_man',
  },
  {
    id: 'major-13',
    name: 'Death',
    arcana: 'major',
    number: 13,
    keywords: ['transformation', 'endings', 'transition', 'change', 'letting go'],
    uprightMeaning:
      'A profound transformation is underway. Something must end so something new can be born — release what no longer serves.',
    reversedMeaning:
      'Resistance to change, stagnation, inability to move on, or a painful transition.',
    imageKey: 'major_death',
  },
  {
    id: 'major-14',
    name: 'Temperance',
    arcana: 'major',
    number: 14,
    keywords: ['balance', 'moderation', 'patience', 'alchemy', 'harmony'],
    uprightMeaning:
      'Balance and patience create something beautiful. Blending opposites with grace leads to healing and wholeness.',
    reversedMeaning:
      'Imbalance, excess, conflict, or a lack of long-term vision.',
    imageKey: 'major_temperance',
  },
  {
    id: 'major-15',
    name: 'The Devil',
    arcana: 'major',
    number: 15,
    keywords: ['bondage', 'materialism', 'shadow', 'addiction', 'illusion'],
    uprightMeaning:
      'Awareness of limiting beliefs, unhealthy attachments, or addictive patterns. The chains can be removed — you hold the key.',
    reversedMeaning:
      'Breaking free from chains, releasing limiting beliefs, or reclaiming personal power.',
    imageKey: 'major_devil',
  },
  {
    id: 'major-16',
    name: 'The Tower',
    arcana: 'major',
    number: 16,
    keywords: ['upheaval', 'chaos', 'revelation', 'sudden change', 'destruction'],
    uprightMeaning:
      'A sudden disruption clears what was built on false foundations. Though turbulent, this awakening leads to liberation.',
    reversedMeaning:
      'Avoiding necessary collapse, delaying inevitable change, or a narrowly avoided disaster.',
    imageKey: 'major_tower',
  },
  {
    id: 'major-17',
    name: 'The Star',
    arcana: 'major',
    number: 17,
    keywords: ['hope', 'renewal', 'inspiration', 'serenity', 'faith'],
    uprightMeaning:
      'After the storm, a star of hope shines. You are guided, renewed, and filled with a quiet, luminous faith.',
    reversedMeaning:
      'Hopelessness, despair, loss of faith, or disconnection from your inner light.',
    imageKey: 'major_star',
  },
  {
    id: 'major-18',
    name: 'The Moon',
    arcana: 'major',
    number: 18,
    keywords: ['illusion', 'fear', 'unconscious', 'mystery', 'dreams'],
    uprightMeaning:
      'Navigate the world of dreams, intuition, and shadow. Not all is as it appears — trust your deeper instincts.',
    reversedMeaning:
      'Confusion lifting, hidden things revealed, or overcoming fear and illusion.',
    imageKey: 'major_moon',
  },
  {
    id: 'major-19',
    name: 'The Sun',
    arcana: 'major',
    number: 19,
    keywords: ['joy', 'success', 'vitality', 'clarity', 'optimism'],
    uprightMeaning:
      'Radiant joy, clarity, and success. Life feels warm and full of possibility. You are shining your authentic light.',
    reversedMeaning:
      'Temporary sadness, blocked joy, or excessive positivity masking truth.',
    imageKey: 'major_sun',
  },
  {
    id: 'major-20',
    name: 'Judgement',
    arcana: 'major',
    number: 20,
    keywords: ['reflection', 'reckoning', 'absolution', 'awakening', 'rebirth'],
    uprightMeaning:
      'A moment of profound awakening and reckoning. Answer the call to rise — forgive the past and step into who you truly are.',
    reversedMeaning:
      'Self-doubt, refusing the call to change, or harsh self-judgment.',
    imageKey: 'major_judgement',
  },
  {
    id: 'major-21',
    name: 'The World',
    arcana: 'major',
    number: 21,
    keywords: ['completion', 'integration', 'accomplishment', 'wholeness', 'travel'],
    uprightMeaning:
      'Completion and wholeness. You have come full circle — celebrate your achievements and prepare for the next great cycle.',
    reversedMeaning:
      'Incompletion, shortcuts, or lingering unfinished business.',
    imageKey: 'major_world',
  },

  // ─────────────────────────────────────────────
  // MINOR ARCANA — WANDS
  // ─────────────────────────────────────────────
  {
    id: 'wands-01',
    name: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 1,
    keywords: ['inspiration', 'new initiative', 'spark', 'potential', 'creativity'],
    uprightMeaning: 'A creative spark ignites. The seed of a new passionate project or venture is ready to be planted.',
    reversedMeaning: 'Delays, lack of motivation, or a good idea that has not yet found its form.',
    imageKey: 'wands_ace',
  },
  {
    id: 'wands-02',
    name: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 2,
    keywords: ['planning', 'future vision', 'progress', 'decisions', 'discovery'],
    uprightMeaning: 'You stand at a crossroads with the world in your hands. Bold plans and long-term vision lead to expansion.',
    reversedMeaning: 'Fear of the unknown, lack of planning, or playing it too safe.',
    imageKey: 'wands_02',
  },
  {
    id: 'wands-03',
    name: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 3,
    keywords: ['expansion', 'foresight', 'overseas', 'preparation', 'enterprise'],
    uprightMeaning: 'Your plans are set in motion. Expansion and opportunity await as your efforts begin to bear fruit.',
    reversedMeaning: 'Obstacles to expansion, delays, or lack of foresight.',
    imageKey: 'wands_03',
  },
  {
    id: 'wands-04',
    name: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 4,
    keywords: ['celebration', 'harmony', 'homecoming', 'community', 'stability'],
    uprightMeaning: 'A time of celebration, milestone achievement, and the joy of community. Welcome home.',
    reversedMeaning: 'Instability at home, postponed celebration, or lack of harmony.',
    imageKey: 'wands_04',
  },
  {
    id: 'wands-05',
    name: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 5,
    keywords: ['conflict', 'competition', 'disagreement', 'chaos', 'diversity'],
    uprightMeaning: 'Competing forces and disagreements create productive tension. Channel the chaos constructively.',
    reversedMeaning: 'Inner conflict, avoiding confrontation, or hidden rivalry.',
    imageKey: 'wands_05',
  },
  {
    id: 'wands-06',
    name: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 6,
    keywords: ['victory', 'success', 'public recognition', 'progress', 'pride'],
    uprightMeaning: 'Public recognition and well-deserved victory. You are being celebrated for your achievements.',
    reversedMeaning: 'Egotism, fall from grace, or success that comes at a cost.',
    imageKey: 'wands_06',
  },
  {
    id: 'wands-07',
    name: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 7,
    keywords: ['challenge', 'perseverance', 'defense', 'competition', 'territory'],
    uprightMeaning: 'Stand your ground. You hold the high position — maintain it with courage and determination.',
    reversedMeaning: 'Overwhelm, giving up, or feeling under attack.',
    imageKey: 'wands_07',
  },
  {
    id: 'wands-08',
    name: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 8,
    keywords: ['speed', 'movement', 'swift action', 'communication', 'air travel'],
    uprightMeaning: 'Events are moving quickly. News is on its way; act swiftly and embrace the rapid flow of energy.',
    reversedMeaning: 'Delays, frustration, slowing momentum, or miscommunication.',
    imageKey: 'wands_08',
  },
  {
    id: 'wands-09',
    name: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 9,
    keywords: ['resilience', 'courage', 'persistence', 'test of faith', 'boundaries'],
    uprightMeaning: 'You are battered but not broken. One final effort will see you through — trust your resilience.',
    reversedMeaning: 'Exhaustion, paranoia, or refusing to continue despite being so close.',
    imageKey: 'wands_09',
  },
  {
    id: 'wands-10',
    name: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 10,
    keywords: ['burden', 'extra responsibility', 'hard work', 'completion', 'overcommitment'],
    uprightMeaning: 'The load is heavy, but the finish line is near. Delegate where possible and honor your limits.',
    reversedMeaning: 'Inability to delegate, burnout, or collapse under pressure.',
    imageKey: 'wands_10',
  },
  {
    id: 'wands-11',
    name: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 11,
    keywords: ['exploration', 'enthusiasm', 'discovery', 'free spirit', 'news'],
    uprightMeaning: 'Enthusiastic, curious, and ready for adventure. A fiery message or the beginning of a passionate pursuit.',
    reversedMeaning: 'Hasty decisions, immaturity, or lack of direction.',
    imageKey: 'wands_page',
  },
  {
    id: 'wands-12',
    name: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 12,
    keywords: ['energy', 'passion', 'adventure', 'impulsiveness', 'action'],
    uprightMeaning: 'Charging forward with passion and fearlessness. Bold action and charismatic energy propel you toward your goals.',
    reversedMeaning: 'Recklessness, impulsiveness, or channeling energy without focus.',
    imageKey: 'wands_knight',
  },
  {
    id: 'wands-13',
    name: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 13,
    keywords: ['courage', 'confidence', 'independence', 'social butterfly', 'determination'],
    uprightMeaning: 'Radiant and courageous, you carry warmth and creative fire. Lead with your heart and inspire others.',
    reversedMeaning: 'Selfishness, jealousy, or dimming your own light for others.',
    imageKey: 'wands_queen',
  },
  {
    id: 'wands-14',
    name: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    number: 14,
    keywords: ['natural leader', 'vision', 'entrepreneur', 'honour', 'bold'],
    uprightMeaning: 'Visionary leadership fueled by passion. You have the authority and fire to turn dreams into empires.',
    reversedMeaning: 'Impulsiveness in leadership, forceful approach, or arrogance.',
    imageKey: 'wands_king',
  },

  // ─────────────────────────────────────────────
  // MINOR ARCANA — CUPS
  // ─────────────────────────────────────────────
  {
    id: 'cups-01',
    name: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 1,
    keywords: ['new feelings', 'emotional awakening', 'love', 'intuition', 'spirituality'],
    uprightMeaning: 'An overflowing cup of emotional and spiritual opportunity. Love, creativity, and compassion pour in.',
    reversedMeaning: 'Repressed emotions, blocked intuition, or emptiness despite apparent abundance.',
    imageKey: 'cups_ace',
  },
  {
    id: 'cups-02',
    name: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 2,
    keywords: ['unity', 'partnership', 'love', 'mutual attraction', 'connection'],
    uprightMeaning: 'A beautiful union — romantic, creative, or soulful. Two people mirror each other with love and respect.',
    reversedMeaning: 'Imbalance, broken partnership, or a connection that has soured.',
    imageKey: 'cups_02',
  },
  {
    id: 'cups-03',
    name: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 3,
    keywords: ['celebration', 'friendship', 'creativity', 'community', 'collaborations'],
    uprightMeaning: 'Joyous celebration with close friends and community. Honor your bonds — abundance is best shared.',
    reversedMeaning: 'Overindulgence, gossip, or exclusion from the group.',
    imageKey: 'cups_03',
  },
  {
    id: 'cups-04',
    name: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 4,
    keywords: ['apathy', 'contemplation', 'disconnectedness', 'reevaluation', 'boredom'],
    uprightMeaning: 'A period of inner contemplation and mild disillusionment. Look up — a new opportunity is being offered.',
    reversedMeaning: 'Emerging from apathy, renewed motivation, or retreat for self-care.',
    imageKey: 'cups_04',
  },
  {
    id: 'cups-05',
    name: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 5,
    keywords: ['loss', 'grief', 'regret', 'disappointment', 'mourning'],
    uprightMeaning: 'Grief and loss are present, but not everything is gone. Turn your gaze to the cups still standing.',
    reversedMeaning: 'Moving on, acceptance, or finding forgiveness after loss.',
    imageKey: 'cups_05',
  },
  {
    id: 'cups-06',
    name: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 6,
    keywords: ['nostalgia', 'childhood', 'innocence', 'joy', 'reunion'],
    uprightMeaning: 'Sweet nostalgia and innocence. Reconnect with your inner child, an old friend, or simpler times.',
    reversedMeaning: 'Living in the past, inability to move forward, or naive idealism.',
    imageKey: 'cups_06',
  },
  {
    id: 'cups-07',
    name: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 7,
    keywords: ['choices', 'fantasy', 'illusion', 'wishful thinking', 'temptation'],
    uprightMeaning: 'Many options dazzle before you, but not all are real. Look beneath the surface before choosing.',
    reversedMeaning: 'Clarity emerging, decisive action, or cutting through confusion.',
    imageKey: 'cups_07',
  },
  {
    id: 'cups-08',
    name: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 8,
    keywords: ['walking away', 'disillusionment', 'seeking deeper meaning', 'departure', 'abandonment'],
    uprightMeaning: 'Courage to leave behind what once fulfilled you. A higher calling beckons — answer it.',
    reversedMeaning: 'Staying in a bad situation out of fear, or avoidance of deeper issues.',
    imageKey: 'cups_08',
  },
  {
    id: 'cups-09',
    name: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 9,
    keywords: ['contentment', 'satisfaction', 'wish fulfillment', 'pleasure', 'well-being'],
    uprightMeaning: 'The wish card. Deep satisfaction and emotional fulfillment. Your heart's desire is within reach.',
    reversedMeaning: 'Smugness, overindulgence, or a wish that comes with strings attached.',
    imageKey: 'cups_09',
  },
  {
    id: 'cups-10',
    name: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 10,
    keywords: ['divine love', 'blissful relationships', 'harmony', 'family', 'alignment'],
    uprightMeaning: 'The rainbow's end — lasting happiness, family harmony, and emotional fulfillment. A life well-loved.',
    reversedMeaning: 'Family conflict, misaligned values, or a fractured sense of home.',
    imageKey: 'cups_10',
  },
  {
    id: 'cups-11',
    name: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 11,
    keywords: ['creative opportunities', 'curiosity', 'news', 'sensitivity', 'imagination'],
    uprightMeaning: 'A gentle message of the heart. Creative dreams surface; remain open to the magical and unexpected.',
    reversedMeaning: 'Immaturity, emotional hypersensitivity, or unrealistic idealism.',
    imageKey: 'cups_page',
  },
  {
    id: 'cups-12',
    name: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 12,
    keywords: ['romance', 'charm', 'imagination', 'following the heart', 'idealism'],
    uprightMeaning: 'An invitation arrives — follow your heart with grace. A romantic idealist in motion.',
    reversedMeaning: 'Moodiness, jealousy, or being led astray by fantasy.',
    imageKey: 'cups_knight',
  },
  {
    id: 'cups-13',
    name: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 13,
    keywords: ['compassion', 'calm', 'intuitive', 'emotional security', 'empathy'],
    uprightMeaning: 'Warm, empathic, and deeply intuitive. She holds space for others while remaining emotionally sovereign.',
    reversedMeaning: 'Codependency, martyrdom, or emotional manipulation.',
    imageKey: 'cups_queen',
  },
  {
    id: 'cups-14',
    name: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    number: 14,
    keywords: ['emotional balance', 'compassion', 'diplomacy', 'wisdom', 'control'],
    uprightMeaning: 'Emotional mastery paired with wisdom. He feels deeply but leads with measured compassion.',
    reversedMeaning: 'Emotional manipulation, volatility, or suppressed feelings.',
    imageKey: 'cups_king',
  },

  // ─────────────────────────────────────────────
  // MINOR ARCANA — SWORDS
  // ─────────────────────────────────────────────
  {
    id: 'swords-01',
    name: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 1,
    keywords: ['breakthroughs', 'clarity', 'truth', 'mental force', 'new ideas'],
    uprightMeaning: 'A burst of mental clarity and truth. Cut through confusion and communicate with precision.',
    reversedMeaning: 'Confusion, chaos, brutality, or using truth as a weapon.',
    imageKey: 'swords_ace',
  },
  {
    id: 'swords-02',
    name: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 2,
    keywords: ['blocked emotions', 'indecision', 'stalemate', 'avoidance', 'balance'],
    uprightMeaning: 'A standoff where no easy choice exists. The blindfold must eventually come off — gather the facts.',
    reversedMeaning: 'Indecision broken, information overload, or a difficult truth finally faced.',
    imageKey: 'swords_02',
  },
  {
    id: 'swords-03',
    name: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 3,
    keywords: ['heartbreak', 'grief', 'sorrow', 'betrayal', 'emotional pain'],
    uprightMeaning: 'Heartbreak and sorrow pierce deeply. Allow yourself to grieve — healing begins when you feel fully.',
    reversedMeaning: 'Recovery from grief, forgiveness, or suppressing pain rather than healing.',
    imageKey: 'swords_03',
  },
  {
    id: 'swords-04',
    name: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 4,
    keywords: ['rest', 'restoration', 'contemplation', 'sanctuary', 'preparation'],
    uprightMeaning: 'Rest and recuperation are essential now. Step back, restore your energy, and return stronger.',
    reversedMeaning: 'Burnout, restlessness, or refusing to slow down.',
    imageKey: 'swords_04',
  },
  {
    id: 'swords-05',
    name: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 5,
    keywords: ['conflict', 'defeat', 'loss', 'self-interest', 'hollow victory'],
    uprightMeaning: 'A win that tastes like ashes. Ask yourself if this conflict is truly worth fighting.',
    reversedMeaning: 'Reconciliation after conflict, or moving past old wounds.',
    imageKey: 'swords_05',
  },
  {
    id: 'swords-06',
    name: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 6,
    keywords: ['transition', 'leaving', 'moving on', 'travel', 'gradual change'],
    uprightMeaning: 'Moving toward calmer waters. A necessary transition — leave troubles behind and sail toward peace.',
    reversedMeaning: 'Resistance to change, unfinished business, or turbulent transitions.',
    imageKey: 'swords_06',
  },
  {
    id: 'swords-07',
    name: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 7,
    keywords: ['deceit', 'strategy', 'self-interest', 'cunning', 'escape'],
    uprightMeaning: 'Someone may not be fully honest — or you may be cutting corners. Strategy and cunning have a role, but integrity matters.',
    reversedMeaning: 'Confession, coming clean, or deceit being exposed.',
    imageKey: 'swords_07',
  },
  {
    id: 'swords-08',
    name: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 8,
    keywords: ['imprisonment', 'entrapment', 'victim mentality', 'restriction', 'powerlessness'],
    uprightMeaning: 'You feel trapped, but the bindings are largely mental. Step carefully and you will find you can walk free.',
    reversedMeaning: 'Breaking free from limitation, new perspective, or releasing self-imposed restrictions.',
    imageKey: 'swords_08',
  },
  {
    id: 'swords-09',
    name: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 9,
    keywords: ['anxiety', 'worry', 'fear', 'nightmares', 'negative thinking'],
    uprightMeaning: 'Anxiety and dark thoughts keep you awake. The mind conjures monsters — bring a light to see them clearly.',
    reversedMeaning: 'Breaking free from anxiety, seeking help, or realizing fears are not reality.',
    imageKey: 'swords_09',
  },
  {
    id: 'swords-10',
    name: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 10,
    keywords: ['painful endings', 'betrayal', 'rock bottom', 'collapse', 'new dawn'],
    uprightMeaning: 'A painful ending, but the sky begins to lighten. What falls here cannot hurt you further — a new dawn follows.',
    reversedMeaning: 'Recovery, resisting the inevitable end, or rising from the ashes.',
    imageKey: 'swords_10',
  },
  {
    id: 'swords-11',
    name: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 11,
    keywords: ['curious', 'restless', 'mental agility', 'new ideas', 'communication'],
    uprightMeaning: 'Sharp-minded and eager to learn. A message is coming, or a new idea demands your attention.',
    reversedMeaning: 'Gossiping, haste, or scattered thinking.',
    imageKey: 'swords_page',
  },
  {
    id: 'swords-12',
    name: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 12,
    keywords: ['ambitious', 'action-oriented', 'driven', 'communicative', 'reckless'],
    uprightMeaning: 'Swift and decisive, charging toward your goal. Powerful action — but ensure you know what you are charging toward.',
    reversedMeaning: 'Recklessness, burnout, or speaking before thinking.',
    imageKey: 'swords_knight',
  },
  {
    id: 'swords-13',
    name: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 13,
    keywords: ['independent', 'analytical', 'clear communication', 'direct', 'complex'],
    uprightMeaning: 'Perceptive, direct, and fair. She sees through pretense and communicates truth with precision and grace.',
    reversedMeaning: 'Cold-heartedness, cruelty, or using wit to wound.',
    imageKey: 'swords_queen',
  },
  {
    id: 'swords-14',
    name: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    number: 14,
    keywords: ['clear thinking', 'intellectual power', 'authority', 'truth', 'ethics'],
    uprightMeaning: 'Intellectual authority and clear, principled judgment. Lead with the mind; let ethics guide every decision.',
    reversedMeaning: 'Abuse of power, manipulation, or cold ruthlessness.',
    imageKey: 'swords_king',
  },

  // ─────────────────────────────────────────────
  // MINOR ARCANA — PENTACLES
  // ─────────────────────────────────────────────
  {
    id: 'pentacles-01',
    name: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 1,
    keywords: ['opportunity', 'prosperity', 'new venture', 'material wealth', 'manifestation'],
    uprightMeaning: 'A golden opportunity arrives in the material realm — career, finances, or health. Plant the seed with intention.',
    reversedMeaning: 'Missed opportunity, greed, or poor financial planning.',
    imageKey: 'pentacles_ace',
  },
  {
    id: 'pentacles-02',
    name: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 2,
    keywords: ['balance', 'adaptability', 'time management', 'prioritization', 'juggling'],
    uprightMeaning: 'Balancing multiple priorities with grace and humor. Stay flexible — the rhythm will find itself.',
    reversedMeaning: 'Disorganization, overextension, or financial imbalance.',
    imageKey: 'pentacles_02',
  },
  {
    id: 'pentacles-03',
    name: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 3,
    keywords: ['teamwork', 'collaboration', 'skill development', 'implementation', 'craftsmanship'],
    uprightMeaning: 'Skilled collaboration creates something greater than the sum of its parts. Master your craft, share your gifts.',
    reversedMeaning: 'Lack of teamwork, poor quality, or ego clashing in collaboration.',
    imageKey: 'pentacles_03',
  },
  {
    id: 'pentacles-04',
    name: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 4,
    keywords: ['holding on', 'security', 'conservation', 'scarcity', 'control'],
    uprightMeaning: 'Careful stewardship of resources, or clinging to what you have out of fear. Security is good; miserliness is not.',
    reversedMeaning: 'Releasing control, generosity, or financial insecurity.',
    imageKey: 'pentacles_04',
  },
  {
    id: 'pentacles-05',
    name: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 5,
    keywords: ['financial loss', 'poverty', 'lack', 'insecurity', 'isolation'],
    uprightMeaning: 'A period of hardship — financial, physical, or emotional. Help is available; do not let pride prevent you from seeking it.',
    reversedMeaning: 'Recovery from hardship, regaining stability, or finding inner resources.',
    imageKey: 'pentacles_05',
  },
  {
    id: 'pentacles-06',
    name: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 6,
    keywords: ['generosity', 'charity', 'giving', 'receiving', 'prosperity'],
    uprightMeaning: 'The flow of giving and receiving is in harmony. Share your abundance and receive with gratitude.',
    reversedMeaning: 'Strings attached gifts, debt, or imbalanced giving.',
    imageKey: 'pentacles_06',
  },
  {
    id: 'pentacles-07',
    name: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 7,
    keywords: ['long-term vision', 'sustainable results', 'perseverance', 'investment', 'reward'],
    uprightMeaning: 'Patience and sustained effort are beginning to bear fruit. Take stock of your progress and plan the next phase.',
    reversedMeaning: 'Impatience, poor investment, or working hard without a plan.',
    imageKey: 'pentacles_07',
  },
  {
    id: 'pentacles-08',
    name: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 8,
    keywords: ['apprenticeship', 'skill development', 'quality', 'dedication', 'craftsmanship'],
    uprightMeaning: 'Diligent, focused practice leads to mastery. Embrace the apprentice mindset and refine your craft.',
    reversedMeaning: 'Perfectionism, lack of ambition, or working without learning.',
    imageKey: 'pentacles_08',
  },
  {
    id: 'pentacles-09',
    name: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 9,
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence', 'reward'],
    uprightMeaning: 'Financial and material independence earned through hard work. Enjoy the fruits of your labor with elegance.',
    reversedMeaning: 'Superficiality, loss of security, or success without fulfillment.',
    imageKey: 'pentacles_09',
  },
  {
    id: 'pentacles-10',
    name: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 10,
    keywords: ['legacy', 'inheritance', 'family wealth', 'long-term success', 'permanence'],
    uprightMeaning: 'Lasting prosperity and legacy. The foundation you build now will sustain generations to come.',
    reversedMeaning: 'Family disputes over wealth, loss of legacy, or unstable foundations.',
    imageKey: 'pentacles_10',
  },
  {
    id: 'pentacles-11',
    name: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 11,
    keywords: ['manifestation', 'financial opportunity', 'new skills', 'studious', 'grounded'],
    uprightMeaning: 'Eager to learn and grow in the material world. New opportunities for skill and prosperity are opening up.',
    reversedMeaning: 'Lack of progress, procrastination, or unrealized potential.',
    imageKey: 'pentacles_page',
  },
  {
    id: 'pentacles-12',
    name: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 12,
    keywords: ['hard work', 'productivity', 'routine', 'conservatism', 'efficiency'],
    uprightMeaning: 'Steady, methodical, and reliable. Progress comes through consistent effort and responsible action.',
    reversedMeaning: 'Laziness, stagnation, or being stuck in an unfulfilling routine.',
    imageKey: 'pentacles_knight',
  },
  {
    id: 'pentacles-13',
    name: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 13,
    keywords: ['nurturing', 'practicality', 'financial security', 'down-to-earth', 'abundance'],
    uprightMeaning: 'Warm, generous, and grounded. She tends to her domain with love, ensuring all who enter feel nurtured and secure.',
    reversedMeaning: 'Neglecting self, financial insecurity, or smothering practicality.',
    imageKey: 'pentacles_queen',
  },
  {
    id: 'pentacles-14',
    name: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    number: 14,
    keywords: ['wealth', 'business', 'leadership', 'security', 'discipline'],
    uprightMeaning: 'Mastery of the material world — financial acumen, disciplined leadership, and enduring success built on integrity.',
    reversedMeaning: 'Financial obsession, corruption, or prioritizing wealth above all else.',
    imageKey: 'pentacles_king',
  },
];

export const MAJOR_ARCANA = TAROT_DECK.filter((c) => c.arcana === 'major');
export const MINOR_ARCANA = TAROT_DECK.filter((c) => c.arcana === 'minor');
export const WANDS = TAROT_DECK.filter((c) => c.suit === 'wands');
export const CUPS = TAROT_DECK.filter((c) => c.suit === 'cups');
export const SWORDS = TAROT_DECK.filter((c) => c.suit === 'swords');
export const PENTACLES = TAROT_DECK.filter((c) => c.suit === 'pentacles');
