ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255),
  ADD COLUMN IF NOT EXISTS smtp_port INTEGER DEFAULT 587,
  ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255),
  ADD COLUMN IF NOT EXISTS smtp_password VARCHAR(255),
  ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(150);
