export interface TarotCard {
  id: string;
  name: string;
  fileName: string;
  arcana: 'mayor' | 'menor';
  suit?: string;
  keywords: string[];
  reading: string;
  readingReversed: string;
}

export const TAROT_CARDS: TarotCard[] = [
  // ── ARCANOS MAYORES ──────────────────────────────────────────────
  {
    id: 'el-loco',
    name: 'El Loco',
    fileName: 'el-loco',
    arcana: 'mayor',
    keywords: ['Inicio', 'Aventura', 'Inocencia'],
    reading: 'El Loco te invita a dar un salto de fe. Es el momento de comenzar algo nuevo con entusiasmo y sin miedo al juicio ajeno. El universo te sostiene cuando actúas desde el corazón. Confía en el viaje, no en el destino.',
    readingReversed: 'Cuidado con la imprudencia y las decisiones apresuradas. Tómate un momento para reflexionar antes de actuar.',
  },
  {
    id: 'el-mago',
    name: 'El Mago',
    fileName: 'el-mago',
    arcana: 'mayor',
    keywords: ['Poder', 'Voluntad', 'Manifestación'],
    reading: 'Tienes todos los recursos que necesitas para crear lo que deseas. El Mago te recuerda que eres el arquitecto de tu propia realidad. Este es el momento de actuar con intención clara y determinación.',
    readingReversed: 'Manipulación o falta de dirección. Usa tu poder con integridad y enfoca tu energía en lo que realmente importa.',
  },
  {
    id: 'la-sacerdotisa',
    name: 'La Sacerdotisa',
    fileName: 'la-sacerdotisa',
    arcana: 'mayor',
    keywords: ['Intuición', 'Misterio', 'Sabiduría interior'],
    reading: 'La Sacerdotisa te pide que confíes en tu voz interior. La respuesta que buscas ya está dentro de ti. Silencia el ruido externo y escucha la sabiduría de tu subconsciente.',
    readingReversed: 'Estás ignorando tu intuición. Los secretos salen a la luz. Presta atención a tus sueños y presentimientos.',
  },
  {
    id: 'la-emperatriz',
    name: 'La Emperatriz',
    fileName: 'la-emperatriz',
    arcana: 'mayor',
    keywords: ['Abundancia', 'Fertilidad', 'Naturaleza'],
    reading: 'La Emperatriz trae abundancia y creatividad a tu vida. Es tiempo de nutrir tus proyectos y relaciones con amor. La naturaleza y la belleza son tus aliadas ahora.',
    readingReversed: 'Bloqueos creativos o dependencia emocional. Reconecta con la naturaleza y cuida de ti mismo antes que de otros.',
  },
  {
    id: 'el-emperador',
    name: 'El Emperador',
    fileName: 'el-emperador',
    arcana: 'mayor',
    keywords: ['Autoridad', 'Estructura', 'Liderazgo'],
    reading: 'Es momento de tomar las riendas de tu vida con determinación. El Emperador te llama a establecer orden, disciplina y límites saludables. Tu poder reside en tu capacidad de liderar con sabiduría.',
    readingReversed: 'Abuso de poder o rigidez excesiva. Flexibiliza tu postura y escucha a los demás.',
  },
  {
    id: 'el-hierofante',
    name: 'El Hierofante',
    fileName: 'el-hierofante',
    arcana: 'mayor',
    keywords: ['Tradición', 'Espiritualidad', 'Guía'],
    reading: 'El Hierofante te conecta con la sabiduría de las tradiciones y la guía espiritual. Puede indicar la necesidad de un mentor, o de profundizar en tus creencias más arraigadas.',
    readingReversed: 'Cuestionamiento de normas establecidas. Es válido buscar tu propio camino espiritual fuera de las instituciones.',
  },
  {
    id: 'los-enamorados',
    name: 'Los Enamorados',
    fileName: 'los-enamorados',
    arcana: 'mayor',
    keywords: ['Amor', 'Elección', 'Unión'],
    reading: 'Los Enamorados hablan de una elección importante desde el corazón. Puede ser en el amor, en valores o en un camino de vida. Actúa desde tu verdad más profunda y no desde el miedo.',
    readingReversed: 'Conflicto interno o disarmonía en una relación. Revisa tus valores y lo que realmente deseas.',
  },
  {
    id: 'el-carro',
    name: 'El Carro',
    fileName: 'el-carro',
    arcana: 'mayor',
    keywords: ['Victoria', 'Control', 'Determinación'],
    reading: 'El Carro anuncia victoria a través de la disciplina y el enfoque. Tienes la fuerza para superar cualquier obstáculo. Mantén el rumbo y no te desvíes por las distracciones.',
    readingReversed: 'Falta de control o dirección. Modera tu agresividad y reconsidera tu estrategia.',
  },
  {
    id: 'la-fuerza',
    name: 'La Fuerza',
    fileName: 'la-fuerza',
    arcana: 'mayor',
    keywords: ['Valentía', 'Paciencia', 'Compasión'],
    reading: 'La verdadera fuerza no es la del músculo sino la del corazón. Enfrenta tus miedos con amor y compasión. La paciencia y la dulzura son tus armas más poderosas ahora.',
    readingReversed: 'Inseguridad o uso excesivo de la fuerza bruta. Reconecta con tu fortaleza interior.',
  },
  {
    id: 'el-ermitano',
    name: 'El Ermitano',
    fileName: 'el-ermitano',
    arcana: 'mayor',
    keywords: ['Soledad', 'Reflexión', 'Búsqueda interior'],
    reading: 'El Ermitano te invita a un período de introspección y retiro. Apaga el ruido del mundo y búscate a ti mismo en el silencio. La sabiduría que necesitas solo puede encontrarse en tu interior.',
    readingReversed: 'Aislamiento excesivo o soledad no deseada. Es momento de reconectarte con el mundo y compartir tu sabiduría.',
  },
  {
    id: 'la-rueda',
    name: 'La Rueda de la Fortuna',
    fileName: 'la-rueda',
    arcana: 'mayor',
    keywords: ['Cambio', 'Ciclos', 'Destino'],
    reading: 'La Rueda de la Fortuna gira y con ella tu vida cambia. Lo que sube debe bajar y viceversa. Acepta los ciclos con gracia y confía en que todo tiene un propósito mayor.',
    readingReversed: 'Mala suerte o resistencia al cambio. Suelta el control y permítete fluir con el río de la vida.',
  },
  {
    id: 'la-justicia',
    name: 'La Justicia',
    fileName: 'la-justicia',
    arcana: 'mayor',
    keywords: ['Equilibrio', 'Verdad', 'Karma'],
    reading: 'La Justicia te recuerda que cada acción tiene su consecuencia. La verdad prevalecerá y el equilibrio será restaurado. Actúa con honestidad e integridad en todos tus asuntos.',
    readingReversed: 'Injusticia o desequilibrio. Revisa tus propias acciones antes de señalar a los demás.',
  },
  {
    id: 'el-colgado',
    name: 'El Colgado',
    fileName: 'el-colgado',
    arcana: 'mayor',
    keywords: ['Pausa', 'Sacrificio', 'Nueva perspectiva'],
    reading: 'El Colgado te pide que te detengas y veas las cosas desde un ángulo completamente distinto. A veces la rendición es el acto más valiente. Este es un tiempo de espera sagrada y transformación.',
    readingReversed: 'Estancamiento por resistencia. Suelta lo que ya no sirve y permite que la transformación ocurra.',
  },
  {
    id: 'la-muerte',
    name: 'La Muerte',
    fileName: 'la-muerte',
    arcana: 'mayor',
    keywords: ['Transformación', 'Fin', 'Renacimiento'],
    reading: 'La Muerte no es el fin sino la transformación más profunda. Algo debe morir para que algo nuevo pueda nacer. Suelta con gracia lo que ya cumplió su ciclo y abraza el renacimiento.',
    readingReversed: 'Resistencia al cambio inevitable. Cuanto más te aferres, más sufrirás. Permítete soltar.',
  },
  {
    id: 'la-templanza',
    name: 'La Templanza',
    fileName: 'la-templanza',
    arcana: 'mayor',
    keywords: ['Equilibrio', 'Moderación', 'Paciencia'],
    reading: 'La Templanza trae equilibrio y armonía. Es tiempo de integrar opuestos, encontrar el término medio y actuar con paciencia. Los mejores resultados vienen de la calma y la moderación.',
    readingReversed: 'Excesos o desequilibrio en algún área de tu vida. Busca el centro y sana lo que está fragmentado.',
  },
  {
    id: 'el-diablo',
    name: 'El Diablo',
    fileName: 'el-diablo',
    arcana: 'mayor',
    keywords: ['Sombra', 'Ataduras', 'Materialismo'],
    reading: 'El Diablo revela las cadenas que tú mismo has creado. Miedos, adicciones, relaciones tóxicas o apego material te mantienen prisionero. La liberación es posible cuando reconoces que las cadenas son ilusorias.',
    readingReversed: 'Liberación de ataduras o reconocimiento de patrones oscuros. El primer paso hacia la libertad ya fue dado.',
  },
  {
    id: 'la-torre',
    name: 'La Torre',
    fileName: 'la-torre',
    arcana: 'mayor',
    keywords: ['Ruptura', 'Revelación', 'Caos'],
    reading: 'La Torre derrumba lo que fue construido sobre bases falsas. Aunque el cambio puede ser abrupto y doloroso, es necesario para tu crecimiento. De las ruinas nace algo más auténtico y sólido.',
    readingReversed: 'El caos se evita pero la lección sigue pendiente. No pospongas lo inevitable.',
  },
  {
    id: 'la-estrella',
    name: 'La Estrella',
    fileName: 'la-estrella',
    arcana: 'mayor',
    keywords: ['Esperanza', 'Renovación', 'Fe'],
    reading: 'La Estrella ilumina tu camino con esperanza y fe renovada. Después de la tormenta llega la calma. Confía en el universo y en tu capacidad de sanar. Eres guiado hacia tu propósito más elevado.',
    readingReversed: 'Desesperanza o desconexión espiritual. Recuerda que incluso la noche más oscura tiene estrellas.',
  },
  {
    id: 'la-luna',
    name: 'La Luna',
    fileName: 'la-luna',
    arcana: 'mayor',
    keywords: ['Ilusión', 'Subconsciente', 'Misterio'],
    reading: 'La Luna te sumerge en las aguas del subconsciente donde habitan miedos e ilusiones. No todo es lo que parece. Presta atención a tus sueños y a la voz que habla en la oscuridad de la noche.',
    readingReversed: 'Las ilusiones se disipan y la verdad emerge. El engaño —propio o ajeno— sale a la luz.',
  },
  {
    id: 'el-sol',
    name: 'El Sol',
    fileName: 'el-sol',
    arcana: 'mayor',
    keywords: ['Alegría', 'Éxito', 'Vitalidad'],
    reading: 'El Sol ilumina todo con su luz radiante. Es un momento de alegría, éxito y claridad. Celebra tus logros y permite que tu luz interior brille sin inhibiciones. La vida te sonríe.',
    readingReversed: 'Alegría temporal bloqueada. Busca dentro la luz que no encuentras afuera.',
  },
  {
    id: 'el-juicio',
    name: 'El Juicio',
    fileName: 'el-juicio',
    arcana: 'mayor',
    keywords: ['Renacimiento', 'Llamado', 'Absolución'],
    reading: 'El Juicio te llama a despertar y responder a tu propósito más elevado. Es tiempo de evaluar tu vida con honestidad, perdonarte a ti mismo y a otros, y abrirte a un nuevo capítulo de existencia.',
    readingReversed: 'Autocrítica excesiva o negativa a escuchar el llamado del alma. Perdónate y sigue adelante.',
  },
  {
    id: 'el-mundo',
    name: 'El Mundo',
    fileName: 'el-mundo',
    arcana: 'mayor',
    keywords: ['Culminación', 'Integración', 'Completitud'],
    reading: 'El Mundo anuncia la culminación de un ciclo importante. Has completado una etapa con maestría. Celebra lo logrado y prepárate para el siguiente nivel de tu viaje. Eres uno con el universo.',
    readingReversed: 'Un ciclo sin cerrar o sensación de incompletitud. Termina lo que empezaste antes de avanzar.',
  },

  // ── ARCANOS MENORES — BASTOS ──────────────────────────────────────
  {
    id: 'as-de-bastos',
    name: 'As de Bastos',
    fileName: 'as-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Inspiración', 'Nuevo inicio', 'Energía'],
    reading: 'El As de Bastos enciende una chispa de inspiración y creatividad. Un nuevo proyecto o pasión está por nacer. Actúa con entusiasmo y aprovecha esta energía vital antes de que se disipe.',
    readingReversed: 'Energía bloqueada o proyectos sin concretar. Identifica qué frena tu creatividad.',
  },
  {
    id: 'dos-de-bastos',
    name: 'Dos de Bastos',
    fileName: 'dos-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Planificación', 'Visión', 'Decisión'],
    reading: 'Estás en el umbral de una gran aventura. El Dos de Bastos te invita a planificar con visión de futuro y dar el primer paso hacia lo que deseas. El mundo está a tus pies.',
    readingReversed: 'Miedo a lo desconocido o falta de planificación. Amplía tu perspectiva.',
  },
  {
    id: 'tres-de-bastos',
    name: 'Tres de Bastos',
    fileName: 'tres-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Expansión', 'Previsión', 'Liderazgo'],
    reading: 'Tus esfuerzos empiezan a dar frutos. El Tres de Bastos indica expansión y nuevas oportunidades en el horizonte, especialmente en viajes o negocios. Mantén tu visión elevada.',
    readingReversed: 'Obstáculos en planes o retrasos frustrantes. La paciencia es clave.',
  },
  {
    id: 'cuatro-de-bastos',
    name: 'Cuatro de Bastos',
    fileName: 'cuatro-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Celebración', 'Hogar', 'Armonía'],
    reading: 'El Cuatro de Bastos trae celebración y armonía al hogar y la comunidad. Es tiempo de festejar los logros compartidos y agradecer por la estabilidad que has construido.',
    readingReversed: 'Tensión en el hogar o celebraciones pospuestas. Busca la armonía perdida.',
  },
  {
    id: 'cinco-de-bastos',
    name: 'Cinco de Bastos',
    fileName: 'cinco-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Conflicto', 'Competencia', 'Desacuerdo'],
    reading: 'El Cinco de Bastos señala competencia y conflictos menores. No todo choque es negativo; a veces la fricción genera crecimiento. Elige tus batallas con sabiduría.',
    readingReversed: 'Conflictos internos o evitar confrontaciones necesarias. Expresa lo que sientes.',
  },
  {
    id: 'seis-de-bastos',
    name: 'Seis de Bastos',
    fileName: 'seis-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Victoria', 'Reconocimiento', 'Triunfo'],
    reading: 'El Seis de Bastos anuncia victoria y reconocimiento público. Tus esfuerzos son vistos y valorados. Acepta el éxito con humildad y comparte el mérito con quienes te apoyaron.',
    readingReversed: 'Ego herido o falta de reconocimiento. El éxito vendrá, pero requiere más trabajo.',
  },
  {
    id: 'siete-de-bastos',
    name: 'Siete de Bastos',
    fileName: 'siete-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Defensa', 'Perseverancia', 'Desafío'],
    reading: 'El Siete de Bastos te llama a defender lo que has logrado. Estás en una posición de ventaja aunque te sientas presionado. Mantente firme en tus convicciones.',
    readingReversed: 'Agotamiento por luchar en demasiados frentes. Establece prioridades claras.',
  },
  {
    id: 'ocho-de-bastos',
    name: 'Ocho de Bastos',
    fileName: 'ocho-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Velocidad', 'Movimiento', 'Acción'],
    reading: 'El Ocho de Bastos indica que todo se acelera. Noticias rápidas, viajes o cambios repentinos están en camino. Prepárate para actuar con rapidez y aprovechar el impulso.',
    readingReversed: 'Retrasos o mensajes mal interpretados. Verifica la información antes de actuar.',
  },
  {
    id: 'nueve-de-bastos',
    name: 'Nueve de Bastos',
    fileName: 'nueve-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Resistencia', 'Guardia', 'Perseverancia'],
    reading: 'Estás casi al final de un largo camino. El Nueve de Bastos pide que te mantengas firme un poco más. Tu resiliencia es tu mayor fortaleza ahora.',
    readingReversed: 'Agotamiento extremo o paranoia. Pide ayuda; no tienes que luchar solo.',
  },
  {
    id: 'diez-de-bastos',
    name: 'Diez de Bastos',
    fileName: 'diez-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Carga', 'Responsabilidad', 'Agotamiento'],
    reading: 'Cargas demasiado sobre tus hombros. El Diez de Bastos te pide que delegues y sueltes algunas responsabilidades. No puedes llegar a la meta si te derrumbas antes.',
    readingReversed: 'Liberación de cargas o colapso inevitable. Es urgente pedir apoyo.',
  },
  {
    id: 'sota-de-bastos',
    name: 'Sota de Bastos',
    fileName: 'sota-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Aventura', 'Entusiasmo', 'Mensaje'],
    reading: 'La Sota de Bastos trae noticias emocionantes y una energía juvenil y creativa. Es tiempo de explorar nuevas ideas con curiosidad y sin miedo al fracaso.',
    readingReversed: 'Impulsividad o proyectos abandonados a medias. Canaliza tu energía con dirección.',
  },
  {
    id: 'caballero-de-bastos',
    name: 'Caballero de Bastos',
    fileName: 'caballero-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Acción', 'Impulsividad', 'Aventura'],
    reading: 'El Caballero de Bastos actúa con pasión y valentía. Su energía empuja hacia adelante sin mirar atrás. Aprovecha este impulso pero cuida de no ser demasiado impulsivo.',
    readingReversed: 'Imprudencia o comportamiento errático. Frena y reflexiona antes de actuar.',
  },
  {
    id: 'reina-de-bastos',
    name: 'Reina de Bastos',
    fileName: 'reina-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Carisma', 'Confianza', 'Pasión'],
    reading: 'La Reina de Bastos irradia confianza y carisma. Lidera desde el corazón con pasión y autenticidad. Este es tu momento de brillar y inspirar a los que te rodean.',
    readingReversed: 'Inseguridad o comportamiento dominante. Reconecta con tu fuego interior.',
  },
  {
    id: 'rey-de-bastos',
    name: 'Rey de Bastos',
    fileName: 'rey-de-bastos',
    arcana: 'menor',
    suit: 'Bastos',
    keywords: ['Liderazgo', 'Visión', 'Maestría'],
    reading: 'El Rey de Bastos es un líder visionario que inspira con su ejemplo. Tienes la madurez y la experiencia para guiar a otros hacia el éxito. Actúa con autoridad y generosidad.',
    readingReversed: 'Autoritarismo o arrogancia. Recuerda que el verdadero líder sirve a su equipo.',
  },

  // ── ARCANOS MENORES — COPAS ───────────────────────────────────────
  {
    id: 'as-de-copas',
    name: 'As de Copas',
    fileName: 'as-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Amor', 'Intuición', 'Nuevo sentimiento'],
    reading: 'El As de Copas desborda amor y nuevos sentimientos. Tu corazón se abre a nuevas conexiones emocionales y espirituales. Permite que el amor fluya libremente hacia ti y desde ti.',
    readingReversed: 'Bloqueo emocional o amor reprimido. Abre tu corazón con valentía.',
  },
  {
    id: 'dos-de-copas',
    name: 'Dos de Copas',
    fileName: 'dos-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Unión', 'Asociación', 'Amor mutuo'],
    reading: 'El Dos de Copas celebra la unión y el amor recíproco. Una relación importante se fortalece o una nueva conexión significativa está por llegar. El equilibrio y el respeto mutuo son la clave.',
    readingReversed: 'Desequilibrio en una relación o ruptura. Comunica lo que sientes.',
  },
  {
    id: 'tres-de-copas',
    name: 'Tres de Copas',
    fileName: 'tres-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Amistad', 'Celebración', 'Comunidad'],
    reading: 'El Tres de Copas invita a celebrar con amigos y seres queridos. La alegría se multiplica cuando se comparte. Es tiempo de festejar los lazos que te nutren y te sostienen.',
    readingReversed: 'Excesos sociales o chismes en el grupo. Cuida la calidad de tus amistades.',
  },
  {
    id: 'cuatro-de-copas',
    name: 'Cuatro de Copas',
    fileName: 'cuatro-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Contemplación', 'Apatía', 'Revaluación'],
    reading: 'El Cuatro de Copas invita a la contemplación, pero cuidado con la apatía. El universo te ofrece nuevas oportunidades que puedes estar ignorando por estar demasiado ensimismado.',
    readingReversed: 'Salir de la apatía o abrirse a nuevas posibilidades. Es tiempo de actuar.',
  },
  {
    id: 'cinco-de-copas',
    name: 'Cinco de Copas',
    fileName: 'cinco-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Pérdida', 'Duelo', 'Lamento'],
    reading: 'El Cinco de Copas habla de pérdida y dolor emocional. Permite que el duelo ocurra, pero recuerda que aún hay copas en pie. No todo está perdido; enfoca tu mirada en lo que permanece.',
    readingReversed: 'Superación del duelo o aceptación de la pérdida. La sanación ha comenzado.',
  },
  {
    id: 'seis-de-copas',
    name: 'Seis de Copas',
    fileName: 'seis-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Nostalgia', 'Infancia', 'Inocencia'],
    reading: 'El Seis de Copas te lleva a los recuerdos del pasado y la inocencia de la infancia. Puede indicar el reencuentro con alguien del pasado o la necesidad de reconectar con tu niño interior.',
    readingReversed: 'Vivir en el pasado o idealizarlo. Es tiempo de mirar hacia adelante.',
  },
  {
    id: 'siete-de-copas',
    name: 'Siete de Copas',
    fileName: 'siete-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Ilusión', 'Elección', 'Fantasía'],
    reading: 'El Siete de Copas presenta muchas opciones, algunas reales y otras ilusorias. Antes de elegir, distingue el deseo genuino de la fantasía escapista. La claridad mental es tu mejor guía ahora.',
    readingReversed: 'Clarity después de la confusión. Las ilusiones se disipan y ves con claridad.',
  },
  {
    id: 'ocho-de-copas',
    name: 'Ocho de Copas',
    fileName: 'ocho-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Abandono', 'Búsqueda', 'Transición'],
    reading: 'El Ocho de Copas invita a dejar atrás lo que ya no te satisface emocionalmente en busca de algo más profundo y significativo. A veces el mayor acto de valentía es alejarse.',
    readingReversed: 'Miedo a dejar ir o regreso a lo familiar. Examina si vuelves por amor o por miedo.',
  },
  {
    id: 'nueve-de-copas',
    name: 'Nueve de Copas',
    fileName: 'nueve-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Satisfacción', 'Deseos', 'Bienestar'],
    reading: 'El Nueve de Copas es la carta del deseo cumplido. Un período de satisfacción emocional y bienestar general se aproxima. Tus deseos más profundos están a punto de materializarse.',
    readingReversed: 'Materialismo o deseos insatisfechos. Examina si lo que deseas realmente te hará feliz.',
  },
  {
    id: 'diez-de-copas',
    name: 'Diez de Copas',
    fileName: 'diez-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Felicidad', 'Familia', 'Armonía'],
    reading: 'El Diez de Copas representa la felicidad familiar y la armonía en el hogar. Tus relaciones más íntimas florecen y el amor te rodea. Este es uno de los mejores augurios en el amor y la familia.',
    readingReversed: 'Disfunción familiar o felicidad aparente. Busca la raíz de los conflictos del hogar.',
  },
  {
    id: 'sota-de-copas',
    name: 'Sota de Copas',
    fileName: 'sota-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Creatividad', 'Intuición', 'Mensaje amoroso'],
    reading: 'La Sota de Copas trae mensajes del corazón y una sensibilidad creativa elevada. Presta atención a tus sueños y a tu intuición. Un mensaje significativo puede llegar de formas inesperadas.',
    readingReversed: 'Inmadurez emocional o dejar llevar por la fantasía. Ancla tus emociones en la realidad.',
  },
  {
    id: 'caballero-de-copas',
    name: 'Caballero de Copas',
    fileName: 'caballero-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Romance', 'Idealismo', 'Propuesta'],
    reading: 'El Caballero de Copas es el romántico del tarot. Trae propuestas, invitaciones y declaraciones de amor. Su corazón habla más alto que su razón. Disfruta la magia pero mantén los pies en la tierra.',
    readingReversed: 'Promesas vacías o decepción romántica. Evalúa las acciones, no solo las palabras.',
  },
  {
    id: 'reina-de-copas',
    name: 'Reina de Copas',
    fileName: 'reina-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Empatía', 'Intuición', 'Cuidado'],
    reading: 'La Reina de Copas es compasiva, empática e intuitiva. Cuida profundamente a los demás desde un lugar de amor incondicional. Es tiempo de honrar tu sensibilidad como una fortaleza.',
    readingReversed: 'Dependencia emocional o descuidar tus propias necesidades. Aprende a recibir el amor que das.',
  },
  {
    id: 'rey-de-copas',
    name: 'Rey de Copas',
    fileName: 'rey-de-copas',
    arcana: 'menor',
    suit: 'Copas',
    keywords: ['Madurez emocional', 'Compasión', 'Equilibrio'],
    reading: 'El Rey de Copas lidera con el corazón sin perder la cabeza. Es el maestro del equilibrio entre emoción y razón. Su sabiduría emocional le permite navegar las aguas más turbulentas con gracia.',
    readingReversed: 'Manipulación emocional o repression de sentimientos. Integra la razón con el corazón.',
  },

  // ── ARCANOS MENORES — ESPADAS ─────────────────────────────────────
  {
    id: 'as-de-espadas',
    name: 'As de Espadas',
    fileName: 'as-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Claridad', 'Verdad', 'Decisión'],
    reading: 'El As de Espadas corta la confusión con claridad absoluta. La verdad emerge y una decisión importante debe ser tomada. Actúa con integridad mental y no temas decir lo que es justo.',
    readingReversed: 'Confusión mental o uso de la verdad como arma. Distingue entre ser honesto y ser cruel.',
  },
  {
    id: 'dos-de-espadas',
    name: 'Dos de Espadas',
    fileName: 'dos-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Bloqueo', 'Decisión difícil', 'Tregua'],
    reading: 'El Dos de Espadas señala un punto muerto o negativa a enfrentar una verdad incómoda. Es tiempo de bajar la guardia, abrir los ojos y tomar la decisión que has estado evitando.',
    readingReversed: 'El bloqueo se libera. Una verdad difícil finalmente puede ser enfrentada.',
  },
  {
    id: 'tres-de-espadas',
    name: 'Tres de Espadas',
    fileName: 'tres-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Dolor', 'Traición', 'Pena'],
    reading: 'El Tres de Espadas señala dolor emocional, traición o ruptura. Permite que las lágrimas fluyan; el dolor es parte del proceso de sanación. Esta herida también enseña y fortalece.',
    readingReversed: 'El dolor comienza a sanar. Forgiveness y recuperación son posibles.',
  },
  {
    id: 'cuatro-de-espadas',
    name: 'Cuatro de Espadas',
    fileName: 'cuatro-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Descanso', 'Recuperación', 'Meditación'],
    reading: 'El Cuatro de Espadas ordena una pausa y descanso profundo. Tu mente y cuerpo necesitan recuperarse. El retiro y la meditación son más productivos ahora que cualquier acción.',
    readingReversed: 'Agitación mental o imposibilidad de descansar. Busca ayuda profesional si el estrés persiste.',
  },
  {
    id: 'cinco-de-espadas',
    name: 'Cinco de Espadas',
    fileName: 'cinco-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Conflicto', 'Derrota', 'Deshonra'],
    reading: 'El Cinco de Espadas advierte que ganar a cualquier costo puede resultar en una pérdida mayor. Reflexiona sobre si esta batalla vale realmente la pena. A veces retirarse es la decisión más sabia.',
    readingReversed: 'Reconciliación o fin de un conflicto. La paz es posible si ambas partes ceden.',
  },
  {
    id: 'seis-de-espadas',
    name: 'Seis de Espadas',
    fileName: 'seis-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Transición', 'Alivio', 'Cambio'],
    reading: 'El Seis de Espadas indica movimiento hacia aguas más tranquilas. Una transición necesaria te aleja de los problemas hacia un período de mayor paz y estabilidad.',
    readingReversed: 'Resistencia al cambio necesario o regreso a situaciones dañinas.',
  },
  {
    id: 'siete-de-espadas',
    name: 'Siete de Espadas',
    fileName: 'siete-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Engaño', 'Estrategia', 'Evasión'],
    reading: 'El Siete de Espadas advierte sobre engaños, ya sea que tú engañes o seas engañado. La honestidad es siempre el mejor camino. Asegúrate de que tu estrategia no comprometa tu integridad.',
    readingReversed: 'Verdades que salen a la luz o consecuencias del engaño. Es tiempo de actuar con honestidad.',
  },
  {
    id: 'ocho-de-espadas',
    name: 'Ocho de Espadas',
    fileName: 'ocho-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Trampa', 'Restricción', 'Impotencia'],
    reading: 'El Ocho de Espadas muestra una prisión mental. Las restricciones que sientes son en gran parte creadas por tu propia mente. Cuando te quites la venda de los ojos, verás que el camino siempre estuvo libre.',
    readingReversed: 'Liberación mental o primeros pasos hacia la libertad. La claridad regresa.',
  },
  {
    id: 'nueve-de-espadas',
    name: 'Nueve de Espadas',
    fileName: 'nueve-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Ansiedad', 'Pesadillas', 'Desesperación'],
    reading: 'El Nueve de Espadas refleja la ansiedad y los pensamientos nocturnos que te roban el sueño. Recuerda que la mente amplifica los miedos en la oscuridad. Busca apoyo y no cargues esto solo.',
    readingReversed: 'Los miedos son menores de lo que parecían. La ansiedad cede y la perspectiva mejora.',
  },
  {
    id: 'diez-de-espadas',
    name: 'Diez de Espadas',
    fileName: 'diez-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Final', 'Traición', 'Renacimiento'],
    reading: 'El Diez de Espadas marca el final doloroso de un ciclo. Aunque parece devastador, después de tocar fondo solo queda subir. De esta crisis nacerá algo completamente nuevo.',
    readingReversed: 'Superación o negativa a reconocer el fin. Acepta el cierre para poder avanzar.',
  },
  {
    id: 'sota-de-espadas',
    name: 'Sota de Espadas',
    fileName: 'sota-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Curiosidad', 'Vigilancia', 'Comunicación'],
    reading: 'La Sota de Espadas observa y analiza todo con mente aguda. Es momento de informarte bien antes de actuar. La comunicación directa y la búsqueda de la verdad son tus herramientas.',
    readingReversed: 'Chismes o uso destructivo de la información. Usa tu inteligencia para construir, no para dañar.',
  },
  {
    id: 'caballero-de-espadas',
    name: 'Caballero de Espadas',
    fileName: 'caballero-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Acción rápida', 'Ambición', 'Impulsividad'],
    reading: 'El Caballero de Espadas actúa con velocidad y determinación. Su energía es poderosa pero puede volverse destructiva sin dirección. Canaliza esta energía hacia un propósito claro.',
    readingReversed: 'Agresividad o precipitación. Piensa antes de actuar y escucha a los demás.',
  },
  {
    id: 'reina-de-espadas',
    name: 'Reina de Espadas',
    fileName: 'reina-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Claridad', 'Independencia', 'Honestidad'],
    reading: 'La Reina de Espadas piensa con claridad y habla con honestidad, sin rodeos. Ha aprendido de sus dolores y los ha transformado en sabiduría. Su independencia es su fortaleza.',
    readingReversed: 'Frialdad o uso de la verdad para herir. Suaviza tu comunicación sin perder la honestidad.',
  },
  {
    id: 'rey-de-espadas',
    name: 'Rey de Espadas',
    fileName: 'rey-de-espadas',
    arcana: 'menor',
    suit: 'Espadas',
    keywords: ['Autoridad', 'Lógica', 'Verdad'],
    reading: 'El Rey de Espadas representa la mente maestra que gobierna con lógica y justicia. Sus decisiones se basan en hechos, no en emociones. Es el momento de actuar con claridad intelectual y autoridad moral.',
    readingReversed: 'Frialdad calculadora o manipulación intelectual. Humaniza tus decisiones con algo de corazón.',
  },

  // ── ARCANOS MENORES — OROS ────────────────────────────────────────
  {
    id: 'as-de-oros',
    name: 'As de Oros',
    fileName: 'as-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Prosperidad', 'Oportunidad', 'Abundancia'],
    reading: 'El As de Oros abre una puerta hacia la prosperidad y la abundancia material. Una nueva oportunidad de negocio, trabajo o inversión se presenta. Recíbela con gratitud y actúa con responsabilidad.',
    readingReversed: 'Oportunidad perdida o mal manejo financiero. Revisa tus gastos y prioridades.',
  },
  {
    id: 'dos-de-oros',
    name: 'Dos de Oros',
    fileName: 'dos-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Equilibrio', 'Adaptabilidad', 'Malabares'],
    reading: 'El Dos de Oros requiere malabarismo y adaptabilidad. Estás equilibrando múltiples responsabilidades a la vez. Mantén la flexibilidad y el buen humor mientras navegas los cambios.',
    readingReversed: 'Desequilibrio financiero o exceso de compromisos. Simplifica y enfócate en lo esencial.',
  },
  {
    id: 'tres-de-oros',
    name: 'Tres de Oros',
    fileName: 'tres-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Trabajo en equipo', 'Habilidad', 'Reconocimiento'],
    reading: 'El Tres de Oros celebra el trabajo bien hecho y la colaboración. Tu habilidad y dedicación son reconocidas. El trabajo en equipo producirá resultados mejores que cualquier esfuerzo individual.',
    readingReversed: 'Falta de trabajo en equipo o habilidades sin desarrollar. Busca colaboración y mejora continua.',
  },
  {
    id: 'cuatro-de-oros',
    name: 'Cuatro de Oros',
    fileName: 'cuatro-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Seguridad', 'Conservación', 'Control'],
    reading: 'El Cuatro de Oros habla de seguridad financiera pero también del riesgo de la avaricia. Proteger lo que tienes es sabio, pero aferrarse demasiado bloquea la abundancia de fluir.',
    readingReversed: 'Generosidad renovada o pérdida de control financiero. Encuentra el balance entre dar y retener.',
  },
  {
    id: 'cinco-de-oros',
    name: 'Cinco de Oros',
    fileName: 'cinco-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Dificultad', 'Pobreza', 'Exclusión'],
    reading: 'El Cinco de Oros señala dificultades materiales o sensación de exclusión. Pero la ayuda existe; quizás solo necesitas pedirla o mirar en otra dirección. Esta situación es temporal.',
    readingReversed: 'Recuperación económica o fin de un período difícil. La luz aparece al final del túnel.',
  },
  {
    id: 'seis-de-oros',
    name: 'Seis de Oros',
    fileName: 'seis-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Generosidad', 'Dar y recibir', 'Caridad'],
    reading: 'El Seis de Oros invita a la generosidad y el equilibrio entre dar y recibir. La prosperidad se multiplica cuando se comparte. Ayuda a quienes lo necesitan y permite que otros también te ayuden.',
    readingReversed: 'Dar con condiciones o desequilibrio en una relación de ayuda.',
  },
  {
    id: 'siete-de-oros',
    name: 'Siete de Oros',
    fileName: 'siete-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Paciencia', 'Inversión', 'Evaluación'],
    reading: 'El Siete de Oros pide paciencia mientras tus esfuerzos maduran. Es tiempo de evaluar lo sembrado y decidir si sigues en el mismo camino o cambias de estrategia. Los resultados llegarán.',
    readingReversed: 'Impaciencia o inversión de tiempo y energía sin retorno. Reconsidera tu estrategia.',
  },
  {
    id: 'ocho-de-oros',
    name: 'Ocho de Oros',
    fileName: 'ocho-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Dedicación', 'Artesanía', 'Perfeccionamiento'],
    reading: 'El Ocho de Oros celebra la dedicación y el perfeccionamiento de habilidades. El trabajo diligente y el aprendizaje continuo son tu camino al éxito. La maestría se construye con práctica constante.',
    readingReversed: 'Perfeccionismo paralizante o trabajo sin dirección. Equilibra la calidad con el avance.',
  },
  {
    id: 'nueve-de-oros',
    name: 'Nueve de Oros',
    fileName: 'nueve-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Abundancia', 'Independencia', 'Lujo'],
    reading: 'El Nueve de Oros celebra la independencia financiera ganada con esfuerzo propio. Es tiempo de disfrutar los frutos de tu trabajo con elegancia y gratitud. La autosuficiencia es tu mayor logro.',
    readingReversed: 'Dependencia financiera o comodidades adquiridas deshonestamente.',
  },
  {
    id: 'diez-de-oros',
    name: 'Diez de Oros',
    fileName: 'diez-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Legado', 'Riqueza', 'Familia'],
    reading: 'El Diez de Oros representa la riqueza duradera y el legado familiar. Tus esfuerzos crean seguridad no solo para ti sino para las generaciones que vienen. La prosperidad es completa y estable.',
    readingReversed: 'Conflictos familiares por dinero o pérdida de legado. Revisa tus prioridades.',
  },
  {
    id: 'sota-de-oros',
    name: 'Sota de Oros',
    fileName: 'sota-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Estudio', 'Oportunidad', 'Manifestación'],
    reading: 'La Sota de Oros trae oportunidades de aprendizaje y crecimiento material. Mantente abierto a nuevas ideas de negocio y formación. La constancia y la dedicación son tu camino hacia el éxito.',
    readingReversed: 'Pereza o proyectos sin concretar. Aterriza tus ideas en acciones concretas.',
  },
  {
    id: 'caballero-de-oros',
    name: 'Caballero de Oros',
    fileName: 'caballero-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Trabajo duro', 'Paciencia', 'Confiabilidad'],
    reading: 'El Caballero de Oros avanza lento pero seguro. Su metodología y paciencia garantizan resultados duraderos. No busca atajos; su dedicación al trabajo bien hecho es su mayor virtud.',
    readingReversed: 'Estancamiento o terquedad que impide el progreso. Sé más flexible y abierto al cambio.',
  },
  {
    id: 'reina-de-oros',
    name: 'Reina de Oros',
    fileName: 'reina-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Prosperidad', 'Practicidad', 'Nutrición'],
    reading: 'La Reina de Oros crea abundancia y seguridad para todos los que la rodean. Es práctica, generosa y tiene un don especial para hacer que las cosas prosperen. Honra tanto tu mundo material como tu bienestar.',
    readingReversed: 'Materialismo o descuido del hogar y la familia. Reequilibra lo material con lo emocional.',
  },
  {
    id: 'rey-de-oros',
    name: 'Rey de Oros',
    fileName: 'rey-de-oros',
    arcana: 'menor',
    suit: 'Oros',
    keywords: ['Abundancia', 'Seguridad', 'Liderazgo'],
    reading: 'El Rey de Oros es el maestro de la abundancia material. Ha construido su prosperidad con paciencia y sabiduría práctica. Su éxito le permite ser generoso y proveer seguridad a quienes le rodean.',
    readingReversed: 'Corrupción o abuso del poder material. El verdadero éxito incluye integridad.',
  },
];

export function getCardByFileName(fileName: string): TarotCard | undefined {
  return TAROT_CARDS.find(c => c.fileName === fileName);
}

export function shuffleCards(count: number): TarotCard[] {
  const shuffled = [...TAROT_CARDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
